export enum Constants {
    DATABASE_CONNECTION = 'DATABASE_CONNECTION',
    DATABASE_COLLECTION_INLINE_COMMENT = 'InlineComment',
    DATABASE_COLLECTION_KYSO_SETTINGS = 'KysoSettings',
    DATABASE_COLLECTION_ORGANIZATION_MEMBER = 'OrganizationMember',
    DATABASE_COLLECTION_TEAM_MEMBER = 'TeamMember',
    DATABASE_COLLECTION_USER = 'User',
    DATABASE_COLLECTION_USER_NOTIFICATIONS_SETTINGS = 'UserNotificationsSettings',
}
